Add permissions by bit array
Not-Riitag/data-controller pull request #6
Opened 2021-10-30 18:54 UTC by bennyman123abc

2021-10-31 05:06 UTC, matthe815 requested changes

2021-10-31 05:06 UTC, matthe815 commented on src/Structs/Permissions.js
> +    }
Make the isArray a single line "if this then nothing else"-type of method with the else-if being on it's own at the bottom.

2021-10-31 05:06 UTC, matthe815 commented on src/Structs/Permissions.js
>      }
Remove `this.permissions = 0` as bitwise does not reapply permissions.

2021-10-31 05:06 UTC, matthe815 commented on src/Structs/Permissions.js
> +            this.permissions == this.permissions | permission;
Similar to the first comment, single-returned-line for the isArray.

2021-11-03 05:17 UTC, bennyman123abc reviewed
Yes

2021-11-03 08:15 UTC, matthe815 approved these changes

2021-11-03 08:16 UTC, merged